### ISSUE TITLE
Deploy de páginas automático com o GitHub Pages!

### ISSUE THREAD

**Issue by bpires** [Nistarin/desafio-4-explorer-rocket.sect#1]
Hey there!

Também estou no explorer e vi que você começou a usar o GitHub recentemente e está colocando seus projetos da rocketseat :clap: essa é uma maneira incrível de documentar a tua jornada!

A dica que eu queria te dar é a de tornar o deploy do seu site automático pelo GitHub Pages. Ele funciona apenas para páginas estáticas, como a deste repositório e as que temos criado até então no Explorer. Assim a gente pode facilmente ver o resultado final das tuas criações! ✨

Quando você ativa o Pages, ele publica o que estiver na página, buscando inicialmente um `index.html`, caso ele não encontre, ele utilizará o `README.md` para gerar a página, e ela ficará acessível no endereço no formato `https://username.github.io/repositoryname/`, assim como seus subrepositórios no `https://username.github.io/repositoryname/subrepositoryname`.

Segue o fio 🧵:

<details>
<summary>1. Com teu repositório aberto, vai em <strong>Settings:</strong></summary>

![image](https://user-images.githubusercontent.com/86871991/162583682-308fe8dc-b818-4332-a5cf-d6d129aec066.png)

</details>

<details>
<summary>2. No menu esquerdo, procura a aba <strong>Pages:</strong></summary>

![image](https://user-images.githubusercontent.com/86871991/162583711-2752046b-6b5b-44fa-8106-6bc9042fb0d0.png)

</details>
<details>
<summary>3. Em <strong>Source</strong>, seleciona a branch <strong>Main:</strong></summary>

![image](https://user-images.githubusercontent.com/86871991/162583899-f6bcabfd-8ff1-4476-b92b-7b7ce54d2021.png)

</details>
<details>
<summary>4. Mantém na pasta <strong>/root</strong> e lembra de <strong>salvar:</strong></summary>

![image](https://user-images.githubusercontent.com/86871991/162583944-df06b6d9-9461-4b1e-9e76-fcf9a4f61f7e.png)

</details>

<details>
<summary>5. Pronto, o GitHub vai fazer o deploy automático do teu repositório e das subpastas para o GitHub Pages, pode levar uns bons minutos (você pode ver o status em "actions"), mas quando terminar você pode ir pela url ou ver na área <strong>Environments</strong> no menu direito do teu repositório a tua página publicada:</summary>

![image](https://user-images.githubusercontent.com/86871991/162584041-18ae4faf-f0bc-4f58-8939-28db18ae23c4.png)

PS: Na área de environments, clica em `github-pages` e depois em `View deployment`

![image](https://user-images.githubusercontent.com/86871991/162584105-4bc18fda-8b97-4381-831c-ad6646037455.png)

</details>

Depois de configurado, toda alteração que você fizer no repositório, ele faz um novo deploy automático!

Testa essa funcionalidade nesse repositório aqui e coloca teu site no ar! 😄

Depois lembra de fechar essa issue.

Keep going! 🔥

---

PS: Não esquece de colocar um README.md no teu repo, assim como em eventuais subrepositórios. Vê como eu fiz aqui: [bpires/rocketseat-explorer/](https://github.com/bpires/rocketseat-explorer) ou nesse excelente [repo do Felipe Vicente](https://github.com/felipe-gomes-vicente/rocket-sect)

E se você quiser algumas ideias de como deixar teus repositórios e perfil do GitHub mais amigáveis, dá uma conferida também nesse site que meu irmão fez: https://readmecreator.herokuapp.com/

Dá para você pegar algumas boas ideias e deixar com a sua cara depois! Abs!

**Comment by Nistarin** [comment]
Opa! 

Ativei aqui o pages e achei bem bacana, não sabia que dava para fazer isso! Hahaha 
Ainda preciso aprender muitas coisas sobre o github, explorei pouquíssimo, então vou dar uma conferida nas suas outras  recomendações!

Um abraço e boa sorte para nós!
